### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by miligithub** [miligithub/WifiFloorplan#1]
- [x]  Room unknown vs pause
- [x]  Select and Delete and Remove axis label
- [x]  Suggest to reverse when stop
- [x]  Image processing group areas (intersection vs union)
- [ ]  Deal with conflicts among different trajs
- [ ]  Plot adjacency graph with weighted links
- [ ] Android Apps draw floor plan
- [ ] Mac version GUI
- [x] Room sizes for smaller rooms
- [ ] Models online (REST API)
